//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class PhotoLabelControl {
    
    /// <summary>
    /// container control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl container;
    
    /// <summary>
    /// _canvasViewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Aurigma.GraphicsMill.AjaxControls.CanvasViewer _canvasViewer;
    
    /// <summary>
    /// zoomInNavigator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Aurigma.GraphicsMill.AjaxControls.ZoomInNavigator zoomInNavigator;
    
    /// <summary>
    /// zoomOutNavigator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Aurigma.GraphicsMill.AjaxControls.ZoomOutNavigator zoomOutNavigator;
    
    /// <summary>
    /// panNavigator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Aurigma.GraphicsMill.AjaxControls.PanNavigator panNavigator;
}
